SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER BillProcessInsert  
ON BillProcess
AFTER INSERT
AS
SET NOCOUNT ON
INSERT BillProcessResults (BillID, ParseFormat)
SELECT BP.ID, PF.ID FROM INSERTED BP JOIN ParseFormats PF ON (PF.Active = 1 )
SET NOCOUNT OFF
GO
